palestra/urls.py
from django.conf.urls import include, url

from . import views


url_list = [
    url(r'^palestra/$', views.PalestraListView.as_view(), name='palestra_list'),
    url(r'^palestra/(?P<slug>[\w-]+)/$', views.PalestraDetailView.as_view(), name='palestra'),
    url(r'^tag/$', views.TipoTagListView.as_view(), name='tipotag_list'),
]

urlpatterns = [
    url(r'', include(url_list, namespace='palestra')),
]

palestrita/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('palestra:tipotag_list'), permanent=False), name='index'),
    url(r'', include('palestra.urls')),
]

palestra/models.py
# -*- coding: utf-8 -*-

from django.core.validators import RegexValidator
from django.db import models
from django.templatetags.static import static
from django.utils.encoding import python_2_unicode_compatible


validate_cor = RegexValidator('^#[0-9A-Fa-f]{6}$')


@python_2_unicode_compatible
class TipoTag(models.Model):
    slug = models.SlugField(primary_key=True)
    nome = models.CharField(max_length=32, unique=True)
    cor = models.CharField(max_length=7, default='#000000', validators=[validate_cor])

    class Meta:
        ordering = ('nome',)

    def __str__(self):
        return self.nome


@python_2_unicode_compatible
class Tag(models.Model):
    tipo = models.ForeignKey(TipoTag, related_name='tags')
    slug = models.SlugField(primary_key=True)
    nome = models.CharField(max_length=32, unique=True)

    class Meta:
        ordering = ('tipo', 'nome')

    def __str__(self):
        return self.nome

    @property
    def cor(self):
        return self.tipo.cor


@python_2_unicode_compatible
class Palestrante(models.Model):
    slug = models.SlugField(primary_key=True)
    nome = models.CharField(max_length=256)
    foto = models.URLField(blank=True)
    info = models.TextField('informações', blank=True)

    class Meta:
        ordering = ('nome',)

    def __str__(self):
        return self.nome

    def has_foto(self):
        return bool(self.foto)
    has_foto.boolean = True
    has_foto.short_description = 'tem foto?'

    def has_info(self):
        return bool(self.info)
    has_info.boolean = True
    has_info.short_description = 'tem info?'

    @property
    def foto_link(self):
        if self.foto:
            return self.foto
        return static('palestra/avatar.png')


@python_2_unicode_compatible
class Palestra(models.Model):
    slug = models.SlugField(primary_key=True)
    nome = models.CharField(max_length=256)
    palestrantes = models.ManyToManyField(Palestrante, related_name='palestras', blank=True)
    tags = models.ManyToManyField(Tag, related_name='palestras', blank=True)
    info = models.TextField('informações', blank=True)

    class Meta:
        ordering = ('nome',)

    def __str__(self):
        return self.nome


@python_2_unicode_compatible
class Video(models.Model):
    palestra = models.ForeignKey(Palestra, related_name='videos')
    url = models.URLField('URL', unique=True)

    class Meta:
        ordering = ('palestra', 'url')
        verbose_name = 'vídeo'

    def __str__(self):
        return self.url

palestra/forms.py
# -*- coding: utf-8 -*-

from django import forms

from . import models


def choices_tag():
    return [(i.nome, list(i.tags.values_list('slug', 'nome')))
            for i in models.TipoTag.objects.all()]


def choices_palestrante():
    palestrantes = list(models.Palestrante.objects.values_list('slug', 'nome'))
    palestrantes.insert(0, ('', '--------------------'))
    return palestrantes


class PalestraPesquisaForm(forms.Form):
    nome = forms.CharField(required=False)
    tag = forms.MultipleChoiceField(label='Nestas tags', required=False, choices=choices_tag)
    excludetag = forms.MultipleChoiceField(label='Não nestas tags', required=False, choices=choices_tag)
    palestrante = forms.ChoiceField(required=False, choices=choices_palestrante)

palestra/views.py
# -*- coding: utf-8 -*-

from django.views import generic

from . import forms
from . import models


class PalestraPesquisaFormMixin(object):
    def get_context_data(self, **kwargs):
        context = super(PalestraPesquisaFormMixin, self).get_context_data(**kwargs)
        context['palestra_pesquisa_form'] = forms.PalestraPesquisaForm(self.request.GET)
        return context


class PalestraListView(PalestraPesquisaFormMixin, generic.ListView):
    model = models.Palestra
    paginate_by = 25

    def get_queryset(self):
        queryset = super(PalestraListView, self).get_queryset()

        filtroform = forms.PalestraPesquisaForm(self.request.GET)
        if filtroform.is_valid():
            if filtroform.cleaned_data['nome']:
                for palavra in filtroform.cleaned_data['nome'].split():
                    queryset = queryset.filter(nome__icontains=palavra)

            if filtroform.cleaned_data['tag']:
                tags = models.Tag.objects.filter(slug__in=filtroform.cleaned_data['tag'])
                for tag in tags:
                    queryset = queryset.filter(tags=tag)

            if filtroform.cleaned_data['excludetag']:
                tags = models.Tag.objects.filter(slug__in=filtroform.cleaned_data['excludetag'])
                for tag in tags:
                    queryset = queryset.exclude(tags=tag)

            if filtroform.cleaned_data['palestrante']:
                palestrante = models.Palestrante.objects.filter(slug=filtroform.cleaned_data['palestrante'])
                queryset = queryset.filter(palestrantes=palestrante)

        queryset = queryset.prefetch_related('palestrantes', 'tags')

        return queryset

    def get_context_data(self, **kwargs):
        context = super(PalestraListView, self).get_context_data(**kwargs)

        query_args = [arg.split('=') for arg in self.request.META['QUERY_STRING'].split('&')]
        query_args = '&'.join('='.join(arg) for arg in query_args if arg[0] != 'page')
        context['query_args'] = query_args

        return context


class PalestraDetailView(PalestraPesquisaFormMixin, generic.DetailView):
    model = models.Palestra

    def get_queryset(self):
        queryset = super(PalestraDetailView, self).get_queryset()
        queryset = queryset.prefetch_related('tags', 'palestrantes', 'videos')
        return queryset


class TipoTagListView(PalestraPesquisaFormMixin, generic.ListView):
    model = models.TipoTag

    def get_queryset(self):
        queryset = super(TipoTagListView, self).get_queryset()
        queryset = queryset.prefetch_related('tags')
        return queryset

palestra/templates/palestra/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load compress %}
<html>
  <head>
    <title>Palestrita</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}
      {% compress css %}
        <link rel="stylesheet" href="{% static 'foundation/css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'foundation/css/foundation.css' %}">
        <link rel="stylesheet" href="{% static 'palestra/base.css' %}">
      {% endcompress %}
    {% endblock %}
    {% block js-head %}
      {% compress js %}
        <script src="{% static 'foundation/js/vendor/modernizr.js' %}"></script>
      {% endcompress %}
    {% endblock %}
  </head>
  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="{% url 'index' %}">Palestrita</a></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
      </ul>
      <section class="top-bar-section">
        <ul class="left">
          <li><a href="{% url 'palestra:tipotag_list' %}">Tags</a></li>
        </ul>
      </section>
    </nav>
    {% include 'palestra/palestra_pesquisa_form.html' %}
    {% block content %}{% endblock %}
    {% block js %}
      {% compress js %}
        <script src="{% static 'foundation/js/vendor/jquery.js' %}"></script>
        <script src="{% static 'foundation/js/foundation.js' %}"></script>
        <script src="{% static 'palestra/base.js' %}"></script>
      {% endcompress %}
    {% endblock %}
  </body>
</html>

palestra/templates/palestra/pagination.html
{% if page_obj.has_other_pages %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="arrow"><a href="?{{ query_args }}&page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% endif %}
    {% for page in paginator.page_range %}
    <li class="{% if page == page_obj.number %}current{% endif %}"><a href="?{{ query_args }}&page={{ page }}">{{ page }}</a></li>
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="arrow"><a href="?{{ query_args }}&page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% endif %}
  </ul>
{% endif %}

palestra/templates/palestra/palestra_detail.html
{% extends 'palestra/base.html' %}
{% load palestras %}


{% block content %}
  <section>
    <div class="row">
      <div class="small-12 columns palestra_detail">
        <h1>{{ palestra }}</h1>
        <div class="row">
          <div class="small-10 columns">
            {% tags_labels palestra.tags.all %}
          </div>
          <div class="small-2 columns text-right">
            {% videos_links palestra.videos.all %}
          </div>
        </div>
        {% videos_players palestra.videos.all %}
        <ul class="small-block-grid-1 medium-block-grid-2">
          {% for palestrante in palestra.palestrantes.all %}
            <li>
              <a href="{% url 'palestra:palestra_list' %}?palestrante={{ palestrante.slug }}">
                <img class="avatar" src="{{ palestrante.foto_link }}" alt="avatar">
                {{ palestrante }}
              </a><br>
              {{ palestrante.info|linebreaksbr|default:'<i>Sem informações</i>' }}
            </li>
          {% endfor %}
        </ul>
        <div class="text-justify">
          {{ palestra.info|linebreaksbr|default:'<i>Sem informações</i>' }}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

palestra/templates/palestra/palestra_list.html
{% extends 'palestra/base.html' %}
{% load palestras %}


{% block content %}
  <section>
    <div class="row">
      <div class="small-12 coluns">
        {% include 'palestra/pagination.html' %}
        <ul class='palestra_list'>
          {% for palestra in palestra_list %}
            <li>
              <h1><a href="{% url 'palestra:palestra' palestra.slug %}">{{ palestra }}</a></h1>
              <ul>
                <li>
                  <b>Palestrante:</b>
                  {% palestrantes_links palestra.palestrantes.all %}
                </li>
                <li>
                  <b>Tags:</b>
                  {% tags_labels palestra.tags.all %}
                </li>
                <li class="text-justify">
                  <b>Info:</b>
                  {{ palestra.info|linebreaksbr|default:'<i>Sem informações</i>' }}
                </li>
              </ul>
            </li>
          {% endfor %}
        </ul>
        {% include 'palestra/pagination.html' %}
      </div>
    </div>
  </section>
{% endblock %}

palestra/templates/palestra/palestra_pesquisa_form.html
<form class="palestra_pesquisa" action="{% url 'palestra:palestra_list' %}">
  <div class="row">
    <div class="small-12 columns">
      {{ form.non_field_errors }}
    </div>
  </div>

  <div class="row collapse">
    <div class="small-8 columns">
      {{ palestra_pesquisa_form.nome }}
    </div>
    <div class="small-4 columns">
      <button class="postfix" type="submit">Pesquisar</button>
    </div>
    <div class="small-12 columns text-right">
      <a class="avancado" href="#">Pesquisa Avançada</a>
    </div>
  </div>

  <div class="row avancada">
    <div class="small-6 large-4 columns">
      {{ palestra_pesquisa_form.tag.label_tag }} {{ palestra_pesquisa_form.tag }}
    </div>
    <div class="small-6 large-4 columns">
      {{ palestra_pesquisa_form.excludetag.label_tag }} {{ palestra_pesquisa_form.excludetag }}
    </div>
    <div class="small-12 large-4 columns">
      {{ palestra_pesquisa_form.palestrante.label_tag }} {{ palestra_pesquisa_form.palestrante }}
    </div>
  </div>
</form>

palestra/templates/palestra/tipotag_list.html
{% extends 'palestra/base.html' %}
{% load palestras %}


{% block content %}
  <section>
    <div class="row">
      <div class="small-12 columns">
        <ul class="square">
          {% for tipotag in tipotag_list %}
            <li>
              <b>{{ tipotag }}</b>
              <ul>
                {% for tag in tipotag.tags.all %}
                  <li>{% tag_label tag %}</li>
                {% endfor %}
              </ul>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </section>
{% endblock %}